[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter prisma exec prisma generate && pnpm --filter api build"

[deploy]
startCommand = "pnpm --filter api start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
